version: "3.7"

services:

  api:
    build: .
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - type: volume
        source: app
        target: /go/bin
    links:
      - db
      - db:database
    container_name: rest_server
    command:
      - --dbdriver=postgres
      - --dbprotocol=postgres
      - --dbusername=postgres
      - --dbpassword=********
      - --dbhost=database
      - --dbname=accounting

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "********"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    container_name: db_server

volumes:
  app:
  dbdata:
    