version: "3.7"

services:

  api:
    build: .
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - type: volume
        source: applogs
        target: /var/log/rest
    links:
      - db
      - db:database
    container_name: rest_server
    command:
      - --dbusername=postgres
      - --dbpassword=322453az
      - --dbhost=database
      - --dbname=accounting

  db:
    image: postgres:9.6.19-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "322453az"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    container_name: db_server

volumes:
  applogs:
  dbdata:
    